import { RouteInfo } from "./vertical-sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "Personal",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    label: "",
    labelClass: "",
    submenu: [],
  },
  {
    path: "dashboard",
    title: "Dashboards",
    icon: "Home",
    class: "has-arrow",
    label: "3",
    labelClass: "side-badge badge badge-info",
    extralink: false,
    submenu: [
      {
        path: "/dashboard/dashboard1",
        title: "Modern",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/dashboard/dashboard2",
        title: "Classic",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/dashboard/dashboard3",
        title: "Analytical",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Masters",
    icon: "server",
    class: "has-arrow",
    label: "",
    labelClass: "",
    extralink: false,
    submenu: [
      {
        path: "/dashboard/dashboard1",
        title: "Customer Accounts",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/dashboard/dashboard2",
        title: "Employee Details",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/dashboard/dashboard3",
        title: "Loan Group",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },{
        path: "/dashboard/dashboard3",
        title: "Employee Designations",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/dashboard/dashboard3",
        title: "Location Details",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
    ],
  }
];
